# Change these first
owner: boriskhodok # Your GitHub organization or username, where this repository lives
repo: wowsuptime # The name of this repository

sites:
  - name: WoWS EU
    url: https://worldofwarships.eu/
  - name: WoWS NA
    url: https://worldofwarships.com/
  - name: WoWS ASIA
    url: https://worldofwarships.asia/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /wowsuptime
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WoWS Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
